language: node_js
node_js: lts/*

env:
  global:
    - MOZ_HEADLESS=1

addons:
  chrome: stable
  firefox: latest
  apt:
    update: true

before_install:
  - sudo apt-get install -y ubuntu-restricted-extras

install:
  - npm install
script:
  - python build/all.py
  - python build/test.py
